CREATE TABLE BLOG
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    URL VARCHAR(1024) NOT NULL,
    NAME VARCHAR(128),
    USER_ID INTEGER
);
CREATE TABLE ITEM
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(2147483647),
    DATE DATE,
    LINK VARCHAR(1024),
    BLOG_ID INTEGER
);
CREATE TABLE ROLE
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(16) NOT NULL
);
CREATE TABLE USER
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(16) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(64),
    ENABLED BOOLEAN
);
CREATE TABLE USER_ROLE
(
    USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL
);
ALTER TABLE ITEM ADD FOREIGN KEY (BLOG_ID) REFERENCES BLOG (ID);
ALTER TABLE BLOG ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);

###########################################################

CREATE TABLE BLOG
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    URL VARCHAR(1024),
    NAME VARCHAR(128),
    USER_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE ITEM
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(128),
    DESCRIPTION VARCHAR(2147483647),
    DATE DATE,
    LINK VARCHAR(1024),
    BLOG_ID INTEGER,
    FOREIGN KEY (BLOG_ID) REFERENCES BLOG (ID),
    FOREIGN KEY (BLOG_ID) REFERENCES BLOG (ID)
);
CREATE TABLE ROLE
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(16) NOT NULL
);
CREATE TABLE USER
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64),
    PASSWORD VARCHAR(128),
    ENABLED BOOLEAN
);
CREATE TABLE USER_ROLE
(
    USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE BLOG
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    URL VARCHAR(1024),
    NAME VARCHAR(128),
    USER_ID INTEGER
);
CREATE TABLE ITEM
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(128),
    DESCRIPTION VARCHAR(2147483647),
    DATE DATE,
    LINK VARCHAR(1024),
    BLOG_ID INTEGER
);
CREATE TABLE ROLE
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(16) NOT NULL
);
CREATE TABLE USER
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64),
    PASSWORD VARCHAR(128),
    ENABLED BOOLEAN
);
CREATE TABLE USER_ROLE
(
    USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL
);

ALTER TABLE BLOG ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE BLOG ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE ITEM ADD FOREIGN KEY (BLOG_ID) REFERENCES BLOG (ID);
ALTER TABLE ITEM ADD FOREIGN KEY (BLOG_ID) REFERENCES BLOG (ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
